Web/Web/Management/Web/ManagementWeb/ViewModels/QuestionViewModel.cs
using Management.Data.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Management.ViewModels
{
    public class QuestionViewModel
    {
        public int Id { get; set; }
        public string Ids { get; set; }

        public string AttributeType { get; set; }
        public string AttributeId { get; set; }
        [UIHint("tinymce_full")]
        [Display(Name = "QuestionDetail")]
        [Required]
        [DataType(DataType.Text, ErrorMessage = "Please write some question")]
        public string QuestionDetail { get; set; }
        [Required]
        public string QuestionTitle { get; set; }

        [UIHint("tinymce_full")]
        [Display(Name = "AnswerDetail")]
        public string AnswerDetail { get; set; }
        [UIHint("tinymce_full")]
        [Display(Name = "ShortAnswerDetail")]
        public string ShortAnswerDetail { get; set; }
        public string Source { get; set; }
        public string Author { get; set; }
        public string Year { get; set; }
        public DateTime Date { get; set; }
        public DateTime LastUpdated { get; set; }
        public QuestionDifficultyLevel QuestionDifficultyLevel { get; set; }
        public int QuestionDifficultyLevelId { get; set; }
        public int QustionTypeId { get; set; }
        public QustionType QustionType { get; set; }
        public string SelectedWord { get; set; }
        public int WordId { get;  set; }
        public bool isEditMode { get; set; }
        public bool IsSetQuestion { get; set; }
        public int SetId { get; set; }
        public List<AdviceViewModel> QuestionChoiceAdvices { get; set; }
        public List<QuestionChoiceViewModel> QuestionChoices { get; set; }
        public string CorrectQuestionChoice { get; set; }
        public string SingleQuestionChoiceAdvice { get; set; }
        public int CorrectQuestionChoiceId { get; set; }
        public List<string> MTQCorrectQuestionChoices { get;  set; }
        public QuestionCategories QuestionCategory { get; set; }
        public bool IsDeleted { get; set; }
        public string Marks { get; set; }
        public decimal AverageSolveMinutes{ get; set; }

    }
}

Web/Web/Management/Web/ManagementWeb/Controllers/QuestionController.cs
using AutoMapper;
using Management.Data.Interfaces.RepositoryInterfaces;
using Management.Data.Interfaces.UnitOfWork;
using Management.Data.Models;
using Management.Infrastructure.Communication;
using Management.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MoreLinq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Management.Controllers
{
    public class QuestionController : Controller
    {
        private readonly ISubjectRepository subjectRepository;
        private readonly IChapterRepository chapterRepository;
        private readonly IUnitOfWork unitOfWork;
        private IHostingEnvironment env;
        private readonly ISectionRepository sectionRepository;
        private readonly ISubSectionRepository subSectionRepository;
        private readonly IQuestionRepository questionRepository;
        private readonly ICorrectAnswerRepository correctAnswerRepository;
        private readonly IWordRepository wordRepository;
        private readonly IWordQuestionRepository wordQuestionRepository;
        private readonly IEmailService emailService;
        private readonly IQuestionTypeRepository questionTypeRepository;
        private readonly IQuestionDifficultyLevelRepository questionDifficultyLevelRepository;
        private readonly IQuestionChoiceRepository questionChoiceRepository;
        private readonly IAnswerRepository answerRepository;
        private readonly IAdviceRepository adviceRepository;
        private readonly IMTQAnsweredChoiceRepository mTQAnsweredChoiceRepository;
        public QuestionController(IMTQAnsweredChoiceRepository _mTQAnsweredChoiceRepository, IAdviceRepository _adviceRepository, IAnswerRepository _answerRepository, IQuestionChoiceRepository _questionChoiceRepository, IQuestionDifficultyLevelRepository _questionDifficultyLevelRepository, IQuestionTypeRepository _questionTypeRepository, IWordRepository _wordRepository, IWordQuestionRepository _wordQuestionRepository, ICorrectAnswerRepository _correctAnswerRepository, IQuestionRepository _questionRepository, IEmailService _emailService, IHostingEnvironment _env, ISubjectRepository _subjectRepository, IChapterRepository _chapterRepository, ISectionRepository _sectionRepository, ISubSectionRepository _subSectionRepository, IUnitOfWork _unitOfWork)
        {
            subjectRepository = _subjectRepository;
            chapterRepository = _chapterRepository;
            unitOfWork = _unitOfWork;
            sectionRepository = _sectionRepository;
            emailService = _emailService;
            subSectionRepository = _subSectionRepository;
            correctAnswerRepository = _correctAnswerRepository;
            questionRepository = _questionRepository;
            wordRepository = _wordRepository;
            wordQuestionRepository = _wordQuestionRepository;
            questionTypeRepository = _questionTypeRepository;
            questionDifficultyLevelRepository = _questionDifficultyLevelRepository;
            answerRepository = _answerRepository;
            questionChoiceRepository = _questionChoiceRepository;
            adviceRepository = _adviceRepository;
            env = _env;
            mTQAnsweredChoiceRepository = _mTQAnsweredChoiceRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin,Researcher,Student")]
        public PartialViewResult GetQuestions(string ids, int wordId)
        {

            ViewBag.WordId = wordId;
            var model = LoadQuestionsList(wordId);
            return PartialView("_ExistingQuestionsList", model);
        }

        [Authorize(Roles = "Admin,Researcher,Student")]
        public PartialViewResult GetExamQuestions(string attributeType, int attributeId)
        {
            var model = LoadExamQuestionsList(attributeType, attributeId);
            return PartialView("_AllExamQuestions", model);
        }

        [Authorize(Roles = "Admin,Researcher")]
        public PartialViewResult GetAvailableQuestions(int attributeId, string attributeType, int wordId)
        {
            var model = LoadAvailableQuestionsList(attributeId, attributeType, wordId);
            return PartialView("_AvailableQuestionsList", model);
        }
        [Authorize(Roles = "Admin,Researcher,Student")]
        private List<QuestionViewModel> LoadQuestionsList(int wordId)
        {
            if (wordId != 0)
            {
                var question = questionRepository.GetManyQuestions(wordId);
                var model = Mapper.Map<List<QuestionViewModel>>(question);
                return model;
            }
            else
            {
                var model = new List<QuestionViewModel>();
                return model;
            }
        }

        [Authorize(Roles = "Admin,Researcher,Student")]
        private List<QuestionViewModel> LoadAvailableQuestionsList(int attributeId, string attributeType, int wordId)
        {

            var question = questionRepository.GetManyAvailableQuestions(attributeId.ToString(), attributeType, 0);

            if (wordId != 0)
            {
                var listWordQuestionIds = wordQuestionRepository.Get().Where(a => a.WordId == wordId).Select(s => s.QuestionId).ToList();
                question = question.Where(a => !listWordQuestionIds.Contains(a.Id)).ToList();
            }



            var model = Mapper.Map<List<QuestionViewModel>>(question);
            return model;
        }
        [Authorize(Roles = "Admin,Researcher,Student")]
        public PartialViewResult Get(string id)
        {
            var question = questionRepository.GetWithAnswer(Convert.ToInt32(id));
            var model = Mapper.Map<QuestionViewModel>(question);

            return PartialView("_Detail", model);
        }

        [Authorize(Roles = "Admin,Researcher,Student")]
        public PartialViewResult GetSetQuestion(string id)
        {
            var question = questionRepository.GetWithAnswer(Convert.ToInt32(id));

            var model = Mapper.Map<QuestionViewModel>(question);
            model.IsSetQuestion = true;
            return PartialView("_Detail", model);
        }
        [Authorize(Roles = "Admin,Researcher")]
        public async Task<BaseModel> AddAvailableQuestion(QuestionViewModel model)
        {
            try
            {
                if (model.Ids != string.Empty)
                {
                    var question = await AddExistingQuestionAsync(model);

                    if (question != null)
                    {
                        return new BaseModel() { Success = true, Message = "Question Added Successfully!", Data = new { QuestionIds = question.Ids, AttributeType = question.AttributeType, WordId = question.WordId } };
                    }
                    else
                    {
                        return BaseModel.Failed("There is an error ");
                    }
                }
                else
                {


                    return BaseModel.Failed("There is an error or you may not entered any question or question title.");

                }
            }
            catch (Exception ex)
            {
                emailService.SendException(ex.Message + "</br></br>" + ex.StackTrace);
                return BaseModel.Failed(ex.Message);
            }

        }

        [Authorize(Roles = "Admin,Researcher")]
        public async Task<BaseModel> AddSubjectQuestion(QuestionViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.QuestionCategory == QuestionCategories.ExamQuestion)
                    {
                        var isQuestionAdded = await AddExamQuestionAsync(AttributeType.Subject, model);

                        if (isQuestionAdded)
                        {
                            return new BaseModel() { Success = true, Message = "Question Added Successfully!" };
                        }
                        else
                        {
                            return BaseModel.Failed("There is an error ");
                        }
                    }
                    else
                    {
                        var question = await AddQuestionAsync(AttributeType.Subject, model);

                        if (question != null)
                        {
                            return new BaseModel() { Success = true, Message = "Question Added Successfully!", Data = new { QuestionIds = question.Ids, AttributeType = AttributeType.Subject, WordId = question.WordId } };
                        }
                        else
                        {
                            return BaseModel.Failed("There is an error ");
                        }
                    }

                }
                else
                {


                    return BaseModel.Failed("There is an error or you may not entered any question or question title.");

                }
            }
            catch (Exception ex)
            {
                emailService.SendException(ex.Message + "</br></br>" + ex.StackTrace);
                return BaseModel.Failed(ex.Message);
            }

        }

        [Authorize(Roles = "Admin,Researcher")]
        public async Task<BaseModel> AddChapterQuestion(QuestionViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.QuestionCategory == QuestionCategories.ExamQuestion)
                    {
                        var isQuestionAdded = await AddExamQuestionAsync(AttributeType.Chapter, model);

                        if (isQuestionAdded)
                        {
                            return new BaseModel() { Success = true, Message = "Question Added Successfully!" };

Web/Web/Management/Web/ManagementWeb/Views/Question/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Web/Web/Management/Web/ManagementWeb/Views/Question/_EditExamQuestionAnswer.cshtml
@model QuestionViewModel
@{
    var isResearcher = User.IsInRole(UserRoles.Researcher.ToString());
    var isAdmin = User.IsInRole(UserRoles.Admin.ToString());
    var isStudent = User.IsInRole(UserRoles.Student.ToString());

}
@if (isResearcher || isAdmin)
{
<form id="editExamQuestionForm" asp-controller="Question" asp-action="UpdateExamQuestionAsync">
    <div asp-validation-summary="ModelOnly" class="ui error message"></div>
    <input asp-for="Id" hidden />
    <input asp-for="AttributeId" hidden />
    <input asp-for="AttributeType" hidden />
    <input asp-for="QuestionCategory" value="@QuestionCategories.ExamQuestion" hidden />

    <input class="QuestionDifficultyLevelId" value="@Model.QuestionDifficultyLevelId" hidden />
    <div class="modal-body">

        <div class="newQuestionSection">

            <h6 class="heading">Update Question Here</h6>

            <div class="row">
                <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">

                    <div class="form-group">
                        <label for="QuestionType">Question Type</label>
                        @{
                            var questionTypes = ViewBag.QuestionTypes as List<QustionType>;
                        }
                        <select id="QustionTypeId" name="QustionTypeId">
                            @foreach (var type in questionTypes)
                            {
                                if (Model.QustionTypeId == type.Id)
                                {
                                    <option selected value="@type.Id">@type.Type</option>
                                }
                                else
                                {
                                    <option value="@type.Id">@type.Type</option>
                                }

                            }
                        </select>
                    </div>
                </div>
                <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="QuestionDifficultyLevel">Difficulty Level</label>
                        <div class="QuestionDifficultyLevel"></div>
                    </div>
                </div>
                <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="Detail">Question Title</label>
                        <input asp-for="QuestionTitle" placeholder="Some starting lines of Question." class="form-control" />
                    </div>
                </div>
                <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="Detail">Marks</label>
                        <input asp-for="Marks" type="number" placeholder="Enter total marks of this Question." class="form-control" />
                    </div>
                </div>
                <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <label for="Detail">Average Solve Time (Minutes)</label>
                        <input asp-for="AverageSolveMinutes" type="number" min="0" placeholder="Enter total Average Solve Minutes of this Question." class="form-control" required />
                    </div>
                </div>
            </div>
            <div class="question-source card">
                <div class="card-header p-2 modal-header">
                    From where it is taken?
                </div>

                <div class="card-body">
                    <div class="row">

                        <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                            <div class="form-group">
                                <label for="Detail">Source</label>
                                <input asp-for="Source" type="text" class="form-control" />

                            </div>

                        </div>
                        <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                            <div class="form-group">
                                <label for="Detail">Author</label>
                                <input asp-for="Author" type="text" class="form-control" />

                            </div>

                        </div>
                        <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                            <div class="form-group">
                                <label for="Detail">Year</label>
                                <input asp-for="Year" type="text" class="form-control Yearpicker" autocomplete="off" />

                            </div>

                        </div>

                    </div>
                </div>

            </div>
            <div class="row">

                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="form-group">
                        <label for="Detail">Question</label>
                        <textarea asp-for="QuestionDetail" class="tmceeditor"></textarea>
                    </div>
                </div>
            </div>

            <div class="row @(Model.QustionTypeId ==Convert.ToInt32( QustionTypesEnum.LongQuestion) ? "" : "hidden") " name="AnswerType" data-questiontype="@QustionTypesEnum.LongQuestion" data-questiontypeid="@Convert.ToInt32(QustionTypesEnum.LongQuestion)">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="form-group">
                        <label for="AnswerDetail">Answer</label>
                        <textarea asp-for="AnswerDetail" class="tmceeditor"></textarea>
                    </div>
                </div>
            </div>

            <div class="row @(Model.QustionTypeId ==Convert.ToInt32( QustionTypesEnum.ShortQuestion)? "" : "hidden") " name="AnswerType" data-questiontype="@QustionTypesEnum.ShortQuestion" data-questiontypeid="@Convert.ToInt32(QustionTypesEnum.ShortQuestion)">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="form-group">
                        <label for="ShortAnswerDetail">Short Answer</label>
                        <textarea asp-for="ShortAnswerDetail" class="tmceeditor"></textarea>
                    </div>
                </div>
            </div>
            <div class="row @(Model.QustionTypeId ==Convert.ToInt32( QustionTypesEnum.MCQ) ? "" : "hidden")" name="AnswerType" data-questiontype="@QustionTypesEnum.MCQ" data-questiontypeid="@Convert.ToInt32(QustionTypesEnum.MCQ)">
                <div class="col note col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="alert  alert-info">Select only correct choice</div>
                </div>
                @if (Model.QustionTypeId == Convert.ToInt32(QustionTypesEnum.MCQ))
                {
                    foreach (var choice in Model.QuestionChoices)
                    {
                        var modalId = Guid.NewGuid();

                        <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-2 Choice">
                            <div class="d-flex">
                                <label class="disableClick">
                                    <input type="radio" name="QuestionChoices" class="radio rounded" @( Model.MTQCorrectQuestionChoices.Contains(choice.Detail) ? "checked" : "") />
                                    <span></span>

                                </label>
                                <textarea class="tmceeditor choice-input" data-id="@choice.Id" placeholder="Enter choice text here" style="height:150px">@choice.Detail</textarea>
                                @*<input class="choice-input" value="@choice.Detail" />*@
                                @*<i class="fas fa-times-circle remove-choice-btn m-2 "></i>*@
                                <span class="badge badge-info adviceBtn mb-3 m-2" data-modalid="@modalId"><i class="fas fa-exclamation-circle"></i> Advice</span>
                                <div></div>


                            </div>
                        </div>
                        if (Model.QuestionChoiceAdvices.FirstOrDefault(a => a.QuestionChoiceId == choice.Id) != null)
                        {
                            <script> createModal("@modalId", `@Model.QuestionChoiceAdvices.FirstOrDefault(a=>a.QuestionChoiceId==choice.Id).Detail`)</script>
                        }
                    }
                }

            </div>
            <div class="row @(Model.QustionTypeId ==Convert.ToInt32( QustionTypesEnum.MTQ) ? "" :  "hidden")" name="AnswerType" data-questiontype="@QustionTypesEnum.MTQ" data-questiontypeid="@Convert.ToInt32(QustionTypesEnum.MTQ)">
                <div class="col note col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="alert  alert-info">Select multiple correct choices</div>
                </div>
                @if (Model.QustionTypeId == Convert.ToInt32(QustionTypesEnum.MTQ))
                {
                    foreach (var choice in Model.QuestionChoices)
                    {
                        var modalId = Guid.NewGuid();

                        <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-2 Choice">
                            <div class="d-flex">
                                <label class="disableClick">
                                    <input type="checkbox" name="QuestionChoices" value="@choice.Detail" class="checkbox squared" @(Model.MTQCorrectQuestionChoices.Contains(choice.Detail) ? "checked" : "") />
                                    <span></span>
                                </label>
                                <textarea class="tmceeditor choice-input" data-id="@choice.Id" placeholder="Enter choice text here" style="height:150px">@choice.Detail</textarea>
                                @*<input class="choice-input" value="@choice.Detail" placeholder="Enter choice text here" />*@
                                @*<i class="fas fa-times-circle m-2 remove-choice-btn"></i>*@
                                <span class="badge badge-info adviceBtn mb-3 m-2" data-modalid="@modalId"><i class="fas fa-exclamation-circle"></i> Advice</span>

                            </div>
                        </div>
                        if (Model.QuestionChoiceAdvices.FirstOrDefault(a => a.QuestionChoiceId == choice.Id) != null)
                        {
                            <script> createModal("@modalId", `@Model.QuestionChoiceAdvices.FirstOrDefault(a=>a.QuestionChoiceId==choice.Id).Detail`)</script>
                        }
                    }
                }
            </div>
            <div class="row  @(Model.QustionTypeId ==Convert.ToInt32( QustionTypesEnum.FillBlank) ? "" :  "hidden") " name="AnswerType" data-questiontype="@QustionTypesEnum.FillBlank" data-questiontypeid="@Convert.ToInt32(QustionTypesEnum.FillBlank)">
                @{var correctQuestionChoice = string.Empty;
                    var fillBlankModalId = string.Empty;
                    if (Model.QustionTypeId == Convert.ToInt32(QustionTypesEnum.FillBlank))
                    {
                        correctQuestionChoice = Model.CorrectQuestionChoice;
                        fillBlankModalId = Guid.NewGuid().ToString();
                        <script> createModal("@fillBlankModalId", "@Model.SingleQuestionChoiceAdvice")</script>
                    }
                }
                <div class="col note col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="alert alert-info">Fill Correct word in the Blank.</div>
                </div>

                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 Choice">
                    <div class="d-flex">
                        <input type="text" name="CorrectQuestionChoice" value="@correctQuestionChoice" class="form-control" placeholder="Fill Correct word in the Blank" />
                        <span class="badge badge-info adviceBtn mb-3 m-2" data-modalid="@fillBlankModalId"><i class="fas fa-exclamation-circle"></i> Advice</span>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="modal-footer pt-2">

        <button type="button" class="btn btn-danger rounded-0" data-dismiss="modal"><i class="fas fa-times"></i> Close</button>

        <button type="submit" class="btn btn-success rounded-0" id="saveBtn"> <i class='fas fa-edit'></i> Update Question </button>

    </div>
</form>
}

Web/Web/Management/Web/ManagementWeb/Views/Question/_EditWrittenQuestionAnswer.cshtml
@model EditQuestionViewModel
@{
    var isResearcher = User.IsInRole(UserRoles.Researcher.ToString());
    var isAdmin = User.IsInRole(UserRoles.Admin.ToString());
    var isStudent = User.IsInRole(UserRoles.Student.ToString());

}
@if (isResearcher || isAdmin)
{
    <form id="editQuestionForm" asp-controller="Question" asp-action="UpdateQuestionAsync">
        <div asp-validation-summary="ModelOnly" class="ui error message"></div>
        <input asp-for="Id" hidden />
        <input asp-for="AttributeId" hidden />
        <input asp-for="AttributeType" hidden />
        <input asp-for="SelectedWord" hidden />
        <input asp-for="QuestionCategory" value="@Model.QuestionCategory" hidden />

        <input class="QuestionDifficultyLevelId" value="@Model.QuestionDifficultyLevel.Id" hidden />
        <input asp-for="WordId" hidden />
        <div class="modal-body">

            <div class="newQuestionSection">

                <h6 class="heading">Update Question Here</h6>

                <div class="row">
                    <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">

                        <div class="form-group">
                            <label for="QuestionType">Question Type</label>

                            <select id="QustionTypeId" name="QustionTypeId">
                                <option selected value="@Convert.ToInt32(QustionTypesEnum.LongQuestion)">Long Question</option>
                            </select>
                        </div>
                    </div>
                    <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <div class="form-group">
                            <label for="QuestionDifficultyLevel">Difficulty Level</label>
                            <div class="QuestionDifficultyLevel"></div>
                        </div>
                    </div>
                </div>
                <div class="question-source card">
                    <div class="card-header p-2 modal-header">
                        From where it is taken?
                    </div>

                    <div class="card-body">
                        <div class="row">

                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <label for="Detail">Source</label>
                                    <input asp-for="Source" type="text" class="form-control" />

                                </div>

                            </div>
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <label for="Detail">Author</label>
                                    <input asp-for="Author" type="text" class="form-control" />

                                </div>

                            </div>
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <label for="Detail">Year</label>
                                    <input asp-for="Year" type="text" class="form-control Yearpicker" autocomplete="off" />

                                </div>

                            </div>

                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label for="Detail">Question Title</label>
                            <input asp-for="EditQuestionTitle" class="form-control" placeholder="Some starting lines of Question." required />
                        </div>
                    </div>
                    <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label for="Detail">Question</label>
                            <textarea asp-for="EditQuestionDetail" class="tmceeditor"></textarea>
                        </div>
                    </div>
                </div>

                <div class="row" name="AnswerType">
                    <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label for="AnswerDetail">Answer</label>
                            <textarea asp-for="EditAnswerDetail" class="tmceeditor"></textarea>

                        </div>
                    </div>
                </div>


            </div>
        </div>
        <div class="modal-footer pt-2">

            <button type="button" class="btn btn-danger rounded-0" data-dismiss="modal"><i class="fas fa-times"></i> Close</button>

            <button type="submit" class="btn btn-success rounded-0" id="saveBtn"> <i class='fas fa-edit'></i> Update Question </button>

        </div>
    </form>
}