Web/Web/Management/Web/ManagementWeb/Controllers/ResearcherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Management.Data.Interfaces.RepositoryInterfaces;
using Management.Data.Interfaces.UnitOfWork;
using Management.Infrastructure.Security.Identity;
using Management.Data.Models;
using AutoMapper;
using Management.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Management.Models;
using Management.Data.Models.CustomModels;
using Management.Infrastructure.Security;
using Management.Infrastructure.Communication;
using Microsoft.EntityFrameworkCore;

namespace Management.Controllers
{

    public class ResearcherController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IEncryptionDecryption security;
        private readonly IEmailService emailService;
        // private readonly RoleManager<IdentityRole> roleManager;
        private IHostingEnvironment env;
        private readonly IUserArtifactRepository userArtifactRepository;
        private readonly IEducationLevelRepository educationLevelRepository;
        private readonly ISubjectRepository subjectRepository;
        private readonly IChapterRepository chapterRepository;

        private readonly IUserChapterRequestRepository userChapterRequestRepository;
        private readonly IUserChapterRepository userChapterRepository;

        private readonly IUserSubjectRequestRepository userSubjectRequestRepository;
        private readonly IUserSubjectRepository userSubjectRepository;
        private readonly IArtifactRepository artifactRepository;
        private readonly IUnitOfWork unitOfWork;
        private readonly RoleManager<Role> roleManager;
        private readonly IUserRoleRepository userRoleManager;
        public ResearcherController(IUserRoleRepository _userRoleManager, RoleManager<Role> _roleManager, IUserChapterRepository _userChapterRepository, IUserChapterRequestRepository _userChapterRequestRepository, IChapterRepository _chapterRepository, IUserSubjectRequestRepository _userSubjectRequestRepository, IEncryptionDecryption _security, IEmailService _emailService, ISubjectRepository _subjectRepository, IEducationLevelRepository _educationLevelRepository, IUserSubjectRepository _userSubjectRepository, IUserArtifactRepository _userArtifactRepository, IHostingEnvironment _env, IArtifactRepository _artifactRepository, UserManager<User> _userManager, IUnitOfWork _unitOfWork)
        {
            educationLevelRepository = _educationLevelRepository;

            userManager = _userManager;
            userRoleManager = _userRoleManager;
            roleManager = _roleManager;
            unitOfWork = _unitOfWork;
            artifactRepository = _artifactRepository;
            env = _env;
            userArtifactRepository = _userArtifactRepository;
            userChapterRequestRepository = _userChapterRequestRepository;
            userChapterRepository = _userChapterRepository;
            userSubjectRequestRepository = _userSubjectRequestRepository;
            userSubjectRepository = _userSubjectRepository;
            subjectRepository = _subjectRepository;
            security = _security;
            emailService = _emailService;
            chapterRepository = _chapterRepository;
        }
        [Authorize(Roles = "Admin,Researcher")]
        public async Task<IActionResult> Index()
        {
            var loggedUser = await userManager.GetUserAsync(User);
            //var isAdmin = await userManager.IsInRoleAsync(loggedUser, UserRoles.Admin.ToString());
            var subjects = subjectRepository.ListOfSubjectsAllocatedToUser(loggedUser.Id, false);

            var subjectsVModel = Mapper.Map<List<SubjectViewModel>>(subjects);
            ViewBag.AllocatedSubjectCount = subjectsVModel.Count;

            var chapters = chapterRepository.ListOfChaptersAllocatedToUser(loggedUser.Id, false);

            var chaptersVModel = Mapper.Map<List<ChapterViewModel>>(chapters);
            ViewBag.AllocatedChapterCount = chaptersVModel.Count;

            ViewBag.SubjectAllocationRequestCount = userSubjectRequestRepository.Get().Where(a => a.UserId == loggedUser.Id && a.StatusId == Convert.ToInt32(RequestsStatus.Pending)).Count();
            ViewBag.ChapterAllocationRequestCount = userChapterRequestRepository.Get().Where(a => a.UserId == loggedUser.Id && a.StatusId == Convert.ToInt32(RequestsStatus.Pending)).Count();

            //ViewBag.EducationLevel = educationLevelRepository.GetEducationLevelWithBoardLevels();
            //ViewBag.Subjects = subjectsVModel;
            //ViewBag.Chapters = subjectsVModel;
            return View();
        }

        [AllowAnonymous]
        public IActionResult ThankYou()
        {
            return View();
        }
        //[Authorize(Roles = "Admin,Researcher")]
        //[HttpGet]
        //public async Task<PartialViewResult> LoadDisciplineMenu()
        //{
        //    ViewBag.EducationLevel = educationLevelRepository.GetEducationLevelWithBoardLevels();
        //    var loggedUser = await userManager.GetUserAsync(User);
        //    var isAdmin = await userManager.IsInRoleAsync(loggedUser, UserRoles.Admin.ToString());
        //    var subjects = subjectRepository.ListOfSubjectsAllocatedToUser(loggedUser.Id,isAdmin);
        //    var subjectsVModel = Mapper.Map<List<SubjectViewModel>>(subjects);

        //    var chapters = chapterRepository.ListOfChaptersAllocatedToUser(loggedUser.Id, isAdmin);
        //    var chaptersVModel = Mapper.Map<List<ChapterViewModel>>(chapters);

        //    ViewBag.Subjects = subjectsVModel;
        //    ViewBag.Chapters = chaptersVModel;
        //    return PartialView("Common/_DisciplineMenu");
        //}
        public IActionResult Register()
        {
            var hashCode = HttpContext.Request.QueryString.ToString();
            hashCode = hashCode.Replace("?u=", "");
            if (!string.IsNullOrEmpty(hashCode))
            {
                var userId = security.DecryptKey(hashCode, true);

                var user = userManager.Users.FirstOrDefault(u => u.Id == userId);
                var researcher = Mapper.Map<UserViewModel>(user);
                if (researcher != null)
                {
                    researcher.IsEditModel = true;

                }

                return PartialView(researcher);
            }
            else
                return View();

        }
        [HttpPost]
        public async Task<BaseViewModel> Register(UserViewModel model)
        {
            try
            {
                var loggedUser = await userManager.GetUserAsync(User);
                var mailModel = new Mail()
                {
                    ToEMailAddress = model.Email,
                    UserName = model.FirstName
                };


                var isUserExist = userManager.Users.Any(u => u.Email == model.Email);
                if (!isUserExist)
                {

                    var user = new User()
                    {
                        Email = model.Email,
                        UserName = model.Email,
                        RegistrationDate = DateTime.Now,
                        IsActive = false,
                        AddedByUser = loggedUser,
                        MobileNumber = model.MobileNumber,
                        Address = model.Address,
                        NationalTaxNumber = model.NationalTaxNumber,
                        CNIC = model.CNIC,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        Gender = model.Gender,
                        PhoneNumber = model.PhoneNumber,
                        SubjectExpertise = model.SubjectExpertise,
                        UserExperienceSummary = model.UserExperienceSummary,
                        YearOfExperience = model.YearOfExperience,

                    };
                    if (string.IsNullOrEmpty(model.Password))
                        await userManager.CreateAsync(user, "Researcher@123");
                    else
                        await userManager.CreateAsync(user, model.Password);

                    var roleId = roleManager.Roles.FirstOrDefault(a => a.Name == UserRoles.Researcher.ToString()).Id;

                    var userRole = new UserRole()
                    {
                        RoleId = roleId,
                        AppRoleId = roleId,
                        UserId = user.Id,
                        AppUserId = user.Id,
                    };
                    await userRoleManager.AddAsync(userRole);

                    //await userManager.AddToRoleAsync(user, UserRoles.Researcher.ToString());
                    await unitOfWork.SaveChangesAsync();
                    if (User != null)
                    {
                        var isAdminLogedin = User.IsInRole(UserRoles.Admin.ToString());

                        if (isAdminLogedin)
                        {
                            mailModel.UserId = user.Id;
                            emailService.ResearcherRegisteredByAdminMail(mailModel);
                        }
                        else
                        {

                            emailService.ResearcherRegisteredMail(mailModel);
                        }
                    }
                    else
                    {

                        emailService.ResearcherRegisteredMail(mailModel);
                    }
                    return new BaseViewModel() { Success = true, Message = "Researcher Added Successfully!!" };

                }
                else
                    return new BaseViewModel() { Success = false, Message = "Email Already Exist!!" };



            }
            catch (Exception ex)
            {
                return new BaseViewModel() { Success = false, Message = ex.Message };

Web/Web/Management/Web/ManagementWeb/Views/Researcher/AllocatedSubjects.cshtml
@model List<SubjectViewModel>
@{
    Html.RenderPartial("~/Views/Shared/Common/AllocatedSubjects.cshtml", Model);
}

Web/Web/Management/Web/ManagementWeb/Views/Researcher/Index.cshtml
<div class=" DashboadPage">
    <div class="badge badge-dark  mb-4 font-size-16 oval-rounded p-3"><i class="ilum ilum-researcher"></i> Researcher</div>

    <!-- /.row -->
    <div class="row">

        <div class=" col-lg-6 col-xl-4 col-md-6 mb-3">
            <a href="#" class="myAllocatedSubjects float-left w-100">
                <div class="custom-card">

                    <div class="custom-card-icon blue">
                        <i class="fas fa-book"></i>
                    </div>
                    <div class="custom-card-body">
                        <div class="huge">@ViewBag.AllocatedSubjectCount</div>
                        <p>My Subjects</p>
                    </div>
                </div>
            </a>
        </div>

        <div class=" col-lg-6 col-xl-4 col-md-6 mb-3">
            <a href="#" class="myAllocatedChapters float-left w-100">
                <div class="custom-card">

                    <div class="custom-card-icon green">
                        <i class="fas fa-book-open"></i>
                    </div>
                    <div class="custom-card-body">
                        <div class="huge">@ViewBag.AllocatedChapterCount</div>
                        <p>My Chapters</p>
                    </div>
                </div>
            </a>
        </div>

        @{
            var addRequestClass = Convert.ToInt32(ViewBag.SubjectAllocationRequestCount) == 0 ? "requestSubjectAllocationOpenBtn" : "showRequestsBtn";
            var text = Convert.ToInt32(ViewBag.SubjectAllocationRequestCount) == 0 ? "Add Subject Request" : "Subject Requests";
            var footerText = Convert.ToInt32(ViewBag.SubjectAllocationRequestCount) == 0 ? "Add Request" : "View Details";
            var iconClass = Convert.ToInt32(ViewBag.SubjectAllocationRequestCount) == 0 ? "ilum-add-request" : "ilum-advice-request";
        }
        <div class=" col-lg-6 col-xl-4 col-md-6 mb-3">
            <a class="@addRequestClass float-left w-100">
                <div class="custom-card">

                    <div class="custom-card-icon orange">
                        <i class="ilum @iconClass"></i>
                    </div>
                    <div class="custom-card-body">
                        <div class="huge">@ViewBag.SubjectAllocationRequestCount</div>
                        <p>@text</p>
                    </div>
                </div>
            </a>
        </div>

        @{
            var addChapterRequestClass = Convert.ToInt32(ViewBag.ChapterAllocationRequestCount) == 0 ? "requestChapterAllocationOpenBtn" : "showChapterRequestsBtn";
            var addChaptertext = Convert.ToInt32(ViewBag.ChapterAllocationRequestCount) == 0 ? "Add Chapter Request" : "Chapter Requests";
            var addChapterfooterText = Convert.ToInt32(ViewBag.ChapterAllocationRequestCount) == 0 ? "Add Request" : "View Details";
            var addChapterIcon = Convert.ToInt32(ViewBag.ChapterAllocationRequestCount) == 0 ? "ilum-add-request" : "ilum-advice-request";
        }
        <div class=" col-lg-6 col-xl-4 col-md-6 mb-3">
            <a class="@addChapterRequestClass float-left w-100">
                <div class="custom-card">

                    <div class="custom-card-icon pink">
                        <i class="ilum @addChapterIcon"></i>
                    </div>
                    <div class="custom-card-body">
                        <div class="huge">@ViewBag.ChapterAllocationRequestCount</div>

                        <p>@addChaptertext</p>
                    </div>
                </div>
            </a>
        </div>

    </div>
</div>
    <!-- /.row -->

Web/Web/Management/Web/ManagementWeb/Views/Researcher/Register.cshtml
@model Management.ViewModels.UserViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title></title>
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/schoolStyle.css" rel="stylesheet" />
    <link href="~/css/sweetalert.css" rel="stylesheet" />
    <link href="~/css/fontawesome-all.css" rel="stylesheet" />
</head>
<body>

    <div class="main">
        <div class="inner-banner">

            <div class="container">
                <div class="row">
                    <h2 class="title-grp">
                        <span>Researcher</span>Registration form
                    </h2>

                </div>
                <span class="float-right text-white"><a class="text-white" href="@Url.Action("Login","Account")">Back to Login</a></span>
            </div>
        </div>

        <section class="field-section">
            <div class="container position-relative">
                <div class="loader text-center hide">
                    <div class="display-table">
                        <div class="display-cell">
                            <i class="fas fa-spinner fa-spin"></i>
                        </div>
                    </div>
                </div>
                <div class="login-icon  col">

                    <img src="~/images/logo.svg" />
                </div>
                <div class="form-cnt mb-5">
                    @{
                        Html.RenderPartial("~/Views/Researcher/_ResearcherRegistraionForm.cshtml", Model);
                    }

                </div>

            </div>


        </section>

    </div>

    <script src="~/js/vendor/jquery.min.js"></script>
    <script src="~/js/vendor/jquery.validate.min.js"></script>
    <script src="~/js/vendor/sweetalert.min.js"></script>
    <script src="/js/jquery.inputmask.bundle.js"></script>
    <script src="~/js/Researcher.js"></script>
    <script src="/js/main.js"></script>


    <script>
        $(document).ready(function () {
            validateResearcherForm();

            $form = $('#addReseacherForm');
            $form.off("submit");
            $form.submit(function (data, event) {

                

                    $('#addReseacherForm button[type=submit]').addClass("disabled");
                    $("body").addClass("stop-scrolling");
                    $('.loader').fadeIn();

                    $.post($(this).attr('action'), $(this).serialize(), function (response) {
                        //can do here
                    }, 'json').done(function (data) {
                        if (data.success) {

                            window.location.href = "/Researcher/ThankYou";
                        } else {
                            swal("Error!!", data.message, "error")
                            $('.loader').fadeOut();
                            $("body").removeClass("stop-scrolling");

                            $('#addReseacherForm button[type=submit]').removeClass("disabled");

                        }

                    });
                    return false;
                

            });

        })

        $(document).on("click", "#saveBtn", function () {
            var isFormValid = $('#addReseacherForm').valid();
            if (isFormValid) {
                $form.submit();
            }
        })
    </script>

</body>
</html>

Web/Web/Management/Web/ManagementWeb/Views/Researcher/ThankYou.cshtml
@model Management.ViewModels.UserViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title></title>
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/schoolStyle.css" rel="stylesheet" />
</head>
<body>

    <div class="main">
        <section class="field-section">
            <div class="container position-relative">
                <div class="display-table">
                    <div class="display-cell">
                        <div class="thanks-card text-center">
                            <h1 class="display-4">Thanks for Registration!</h1>
                            <p>We will be in touch with you soon.</p>
                            <p><a href="/Account/Login">Login Here</a></p>
                        </div>
                    </div>
                </div>

            </div>


        </section>

    </div>

  
</body>
</html>

Web/Web/Management/Web/ManagementWeb/Views/Researcher/_InviteResearcherForm.cshtml
@model Management.Data.Models.CustomModels.Mail

<form id="inviteResearcherForm" asp-action="ResearcherInvite" asp-controller="Researcher">
    <!-- Modal body -->
    <div class="modal-body">

        <div class="row">
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input asp-for="UserName" type="text" required placeholder="User's Name" />
                </div>
            </div>
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input asp-for="ToEMailAddress" type="email" required placeholder="Researcher email address" />
                </div>
            </div>
        </div>

    </div>

    <!-- Modal footer -->
    <div class="modal-footer pt-2">
        <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <div class="form-group">
                <button type="button" class="btn btn-danger rounded-0" data-dismiss="modal">Close</button>
            </div>
        </div>
        <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <div class="form-group">
                <button type="submit" class="btn btn-success rounded-0" id="saveBtn">Send</button>
            </div>
        </div>
    </div>
</form>

Web/Web/Management/Web/ManagementWeb/Views/Researcher/_ResearcherRegistraionForm.cshtml
@model UserViewModel

@{
    var action = "Register";
    if (Model != null)
    {
        if (Model.IsEditModel)
        {
            action = "UpdateResearcher";
        }
    }

}
<form id="addReseacherForm" asp-controller="Researcher" asp-action="@action">
    <!-- Modal body -->
    <div class="modal-body">
        <p>All Fields are mandatory.</p>
        <div class="row">

            <input type="text" asp-for="Id" placeholder="First Name" hidden />
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input type="text" asp-for="FirstName" placeholder="First Name" required />
                </div>
            </div>
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6-col-xl-6">
                <div class="form-group">
                    <input type="text" asp-for="LastName" placeholder="Last Name" required />
                </div>
            </div>
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    @{
                        var email = "";
                        if (!string.IsNullOrEmpty(ViewBag.Email))
                        {
                            email = ViewBag.Email;
                            <input type="email" asp-for="Email" value="@email" placeholder="Email" required />
                        }
                        else
                        {
                            <input type="email" asp-for="Email" placeholder="Email" required />
                        }
                    }
                </div>
            </div>
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input type="text" asp-for="CNIC" data-inputmask="'mask': '99999-9999999-9'" placeholder="XXXXX-XXXXXXX-X" required />
                </div>
            </div>
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input type="text" asp-for="MobileNumber" placeholder="Mobile Number" required />
                </div>
            </div>

            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input type="text" asp-for="PhoneNumber" placeholder="Phone Number (Optional)" />
                </div>
            </div>
            <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="form-group">
                    <input type="text" asp-for="Address" placeholder="Address" required />
                </div>
            </div>
            <div class="col col-12 col-sm-6 col-md-6 col-lg-6-col-xl-6">
                <div class="form-group">
                    <input type="text" asp-for="NationalTaxNumber" placeholder="NTN" required />
                </div>
            </div>

            <div class="col col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input type="text" asp-for="SubjectExpertise" placeholder="Subject Expertise" required />
                </div>
            </div>
            <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="form-group">
                    <textarea type="text" asp-for="UserExperienceSummary" placeholder="Experience Summary" required></textarea>
                </div>
            </div>
            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <input type="number" asp-for="YearOfExperience" placeholder="Year Of Experience" required />
                </div>
            </div>


            @if (!User.IsInRole(UserRoles.Admin.ToString()))
            {


                <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                    <div class="form-group">
                        <input type="password" asp-for="Password" placeholder="e.g. Password@@123" required />
                    </div>
                </div>

            }
            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <label class="gender-label"> @Html.RadioButton("Gender", "Male", true) <span> Male</span></label>
                    <label class="gender-label"> @Html.RadioButton("Gender", "Female")  <span>Female</span></label>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal footer -->
    <div class="modal-footer pt-2">
        @if (User.IsInRole(UserRoles.Admin.ToString()))
        {
            <button type="button" class="btn btn-danger rounded-0" data-dismiss="modal"><i class="fas fa-times"></i> Close</button>
        }
        <button type="button" class="btn btn-success rounded-0" id="saveBtn"><i class="fas fa-user-plus"></i> Register</button>
    </div>
</form>