Web/Web/Management/Web/ManagementWeb/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Management.Data.Interfaces.RepositoryInterfaces;
using Management.ViewModels;
using Management.Data.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using HtmlAgilityPack;
using Management.Data.Interfaces.UnitOfWork;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Management.Infrastructure.Communication;
using Microsoft.AspNetCore.Identity;
using AutoMapper;
using Management.Data.Models.CustomModels;
using Microsoft.AspNetCore.Http;
using Management.Filters;
using Microsoft.Extensions.Caching.Memory;

namespace Management.Controllers
{
    public class BookController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly ISubjectRepository subjectRepository;
        private readonly IChapterRepository chapterRepository;
        private readonly IWordRepository wordRepository;
        private readonly IUnitOfWork unitOfWork;
        private readonly ICorrectAnswerRepository correctAnswerRepository;
        private readonly IUserSubjectRequestRepository userSubjectRequestRepository;
        private readonly IUserSubjectRepository userSubjectRepository;
        private readonly IQuestionRepository questionRepository;
        private IHostingEnvironment env;
        private readonly ICommentaryRepository commentaryRepository;
        private readonly ISectionRepository sectionRepository;
        private readonly ISubSectionRepository subSectionRepository;
        private readonly IQuestionTypeRepository questionTypeRepository;
        private readonly IQuestionDifficultyLevelRepository questionDifficultyLevelRepository;
        private readonly IEducationLevelRepository educationLevelRepository;
        private readonly IEmailService emailService;
        private IMemoryCache cache;

        private readonly IUserChapterRepository userChapterRepository;
        private readonly IUserChapterRequestRepository userChapterRequestRepository;
        public BookController(IMemoryCache memoryCache,IUserChapterRepository _userChapterRepository, IUserChapterRequestRepository _userChapterRequestRepository, IEducationLevelRepository _educationLevelRepository, IQuestionRepository _questionRepository, ICommentaryRepository _commentaryRepository, ICorrectAnswerRepository _correctAnswerRepository, IWordRepository _wordRepository, IUserSubjectRequestRepository _userSubjectRequestRepository, UserManager<User> _userManager, IUserSubjectRepository _userSubjectRepository, IQuestionDifficultyLevelRepository _questionDifficultyLevelRepository, IQuestionTypeRepository _questionTypeRepository, IEmailService _emailService, IHostingEnvironment _env, ISubjectRepository _subjectRepository, IChapterRepository _chapterRepository, ISectionRepository _sectionRepository, ISubSectionRepository _subSectionRepository, IUnitOfWork _unitOfWork)
        {
            userManager = _userManager;
            userChapterRequestRepository = _userChapterRequestRepository;
            subjectRepository = _subjectRepository;
            userSubjectRequestRepository = _userSubjectRequestRepository;
            userSubjectRepository = _userSubjectRepository;
            chapterRepository = _chapterRepository;
            unitOfWork = _unitOfWork;
            commentaryRepository = _commentaryRepository;
            wordRepository = _wordRepository;
            educationLevelRepository = _educationLevelRepository;
            correctAnswerRepository = _correctAnswerRepository;
            sectionRepository = _sectionRepository;
            emailService = _emailService;
            subSectionRepository = _subSectionRepository;
            questionRepository = _questionRepository;
            questionTypeRepository = _questionTypeRepository;
            questionDifficultyLevelRepository = _questionDifficultyLevelRepository;
            env = _env;
            userChapterRepository = _userChapterRepository;
            cache = memoryCache;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View("Layouts/_BookNew");
        }
      
        [Authorize(Roles = "Admin,Researcher,Teacher")]
        public async Task<BaseViewModel> DeleteDetailForSubject(int id)
        {
            var existingModel = subjectRepository.Get().FirstOrDefault(a => a.Id == id);
            existingModel.Detail = string.Empty;
            await subjectRepository.UpdateAsync(existingModel);
            await unitOfWork.SaveChangesAsync();

            return new BaseViewModel() { Success = true, Message = "Removed Detail Successfully!!" };
        }

        [Authorize(Roles = "Admin,Researcher,Teacher")]
        public BaseViewModel LoadSubjectDetail(int id)
        {
            var existingModel = subjectRepository.Get().FirstOrDefault(a => a.Id == id);

            return new BaseViewModel() { Data = existingModel };
        }
        [Authorize(Roles = "Admin,Researcher,Teacher,Student")]
        public async Task<PartialViewResult> LoadSubjectDetailView(int id)
        {
            var existingModel = subjectRepository.Get().FirstOrDefault(a => a.Id == id);
            var loggedUser = await userManager.GetUserAsync(User);
            var isAdmin = await userManager.IsInRoleAsync(loggedUser, UserRoles.Admin.ToString());
            var isAttributeAllocated = userSubjectRepository.Get().Any(a => a.SubjectId == id && a.UserId == loggedUser.Id && a.IsActive);
            if (isAttributeAllocated || isAdmin)
            {
                var attribute = new AttributeViewModel()
                {
                    Id = existingModel.Id,
                    Name = existingModel.Name,
                    Type = AttributeType.Subject,
                    Detail = existingModel.Detail,
                    TypeText = AttributeType.SubjectText
                };
                return PartialView("_DescriptionWrapper", attribute);
            }
            else
            {
                return new NotAllowedViewResult();

            }

        }
        [Authorize(Roles = "Admin,Researcher,Teacher")]
        public async Task<IActionResult> EditSubject(int id)
        {

            var subject = subjectRepository.Get().FirstOrDefault(a => a.Id == id);
            if (subject != null)
            {
                ViewBag.AttributeType = AttributeType.Subject;
                ViewBag.EducationLevel = educationLevelRepository.GetEducationLevelWithBoardLevels();

                var loggedUser = await userManager.GetUserAsync(User);
                var isAdmin = await userManager.IsInRoleAsync(loggedUser, UserRoles.Admin.ToString());
                var isAttributeAllocated = userSubjectRepository.Get().Any(a => a.SubjectId == id && a.UserId == loggedUser.Id && a.IsActive);
                if (isAttributeAllocated || isAdmin)
                {
                    var childAttributes = subject.Chapters;
                    var childAttributesModel = new List<AttributeViewModel>();
                    foreach (var child in childAttributes)
                    {
                        var childAttributeModel = new AttributeViewModel()
                        {
                            Id = child.Id,
                            Name = child.Name,
                            Type = AttributeType.Chapter,
                            TypeText = AttributeType.Chapter
                        };
                        childAttributesModel.Add(childAttributeModel);
                    }

                    ViewBag.Attributes = childAttributesModel;

                    //ViewBag.Subject = subject;
                    ViewBag.QuestionTypes = questionTypeRepository.Get().ToList();
                    ViewBag.QuestionDifficultyLevels = questionDifficultyLevelRepository.Get().ToList();


                    var attribute = new AttributeViewModel()
                    {
                        Id = subject.Id,
                        Detail = subject.Detail,
                        Name = subject.Name,
                        Type = AttributeType.Subject,
                        TypeText = AttributeType.SubjectText,
                        ParentId = subject.ClassId,
                        ParentType = AttributeType.Class
                    };
                    return View("EditDetail", attribute);
                }
                else
                {
                    return new NotAllowedViewResult();

                }

            }
            else
            {
                return new NotFoundViewResult();
            }
        }

        [Authorize(Roles = "Admin,Researcher,Teacher,Student")]
        public async Task<IActionResult> Subject(int id)
        {
            try
            {
                if (id != 0)
                {
                    var subject = subjectRepository.GetWithChapters(id);
                    if (subject != null)
                    {
                        ViewBag.AttributeType = AttributeType.Subject;
                        var loggedUser = await userManager.GetUserAsync(User);
                        var isAdmin = await userManager.IsInRoleAsync(loggedUser, UserRoles.Admin.ToString());
                        var isAttributeAllocated = userSubjectRepository.Get().Any(a => a.SubjectId == id && a.UserId == loggedUser.Id && a.IsActive);
                        if (isAttributeAllocated || isAdmin)
                        {
                            ViewBag.EducationLevel = educationLevelRepository.GetEducationLevelWithBoardLevels();

                            var childAttributes = subject.Chapters;
                            var childAttributesModel = new List<AttributeViewModel>();
                            foreach (var child in childAttributes)
                            {
                                   var childAttributeModel = new AttributeViewModel()

Web/Web/Management/Web/ManagementWeb/Views/Book/Detail.cshtml
@model AttributeViewModel
@{
    var isResearcher = User.IsInRole(UserRoles.Researcher.ToString());
    var isAdmin = User.IsInRole(UserRoles.Admin.ToString());
    var isStudent = User.IsInRole(UserRoles.Student.ToString());

}
<div class="col col-12">
    @*<a class="custom-button btn-blue oval-rounded mb-3 float-left mr-2" href="/#@(Model.ParentType+"_"+Model.ParentId)" data-attributetype="@Model.ParentType" data-attributeid="@Model.ParentId" data-toggle="tooltip" data-placement="left" title="Go back to @Model.ParentType"> <i class="fas fa-chevron-left"></i> </a>*@

    <a class="custom-button btn-blue oval-rounded mb-3 viewbutton float-left mr-2" data-attributetype="@Model.ParentType" data-attributeid="@Model.ParentId" data-toggle="tooltip" data-placement="left" title="Go back to @Model.ParentType"> <i class="fas fa-chevron-left"></i> </a>
    @if (!string.IsNullOrEmpty(Model.Detail))
    {

        @if (isResearcher || isAdmin)
        {
            <a class="custom-button btn-blue oval-rounded mb-3 loadDocumentBtn"> <i class="fas fa-book"></i> Load Other Document Here </a>

        }
            <div class="page-outline main-page pt-6 pr-5 pl-5 pb-3 mb-4">
                @if (isResearcher || isAdmin)
                {
                    <div class="actionBtns position-absolute">
                        @if (isAdmin)
                        {
                            <i class="fas fa-envelope  emailAllocatedMember" data-attributetype="@Model.Type" data-attributeid="@Model.Id" data-toggle="tooltip" title="Inform Student/Researcher regarding new changes in this @Model.TypeText"></i>
                            <i class="fas fa-print printPageBtn" data-toggle="tooltip" data-placement="left" title="Print Document"></i>
                        }

                        <i class="fas fa-search-plus" id="ZoomIn" data-toggle="tooltip" data-placement="left" title="Zoom In"></i>
                        <i id="ZoomReset" class="fas fa-history" data-toggle="tooltip" data-placement="left" title="Reset Zoom"></i>
                        <i class="fas fa-search-minus" id="ZoomOut" data-toggle="tooltip" data-placement="left" title="Zoom Out"></i>

                        <a href="@Url.Action("Edit" + Model.Type, "Book")?id=@Model.Id"> <i class="fas fa-edit" data-toggle="tooltip" data-placement="left" title="Edit Document"></i></a>
                        <i class="fas fa-trash deleteDetailBtn" data-toggle="tooltip" data-placement="left" data-modalcall="true" data-type="@Model.Type" data-id="@Model.Id" title="Delete Document"> </i>
                    </div>
                }

            @if (isResearcher || isAdmin)
            {
                @*<div class="question-box p-2">
                        <i class="fas fa-chevron-left "></i>
                        <div class="btns" style="display:none">
                            <a class="rounded-left" data-toggle="tooltip" title="Show all questions"><i class="fas fa-question"></i>  </a>
                            <a class="rounded-right" data-toggle="tooltip" title="Add a question to this @Model.TypeText"><i class="fas fa-plus "></i> </a>

                        </div>
                    </div>*@

                    <button class="addQuestionToWord rounded" type="button">
                        <i class="fas fa-plus"></i>
                    </button>


                }

                @*<a class="backToNavigationWord hidden" data-toggle="tooltip" title="Back to Last Position" style="display:none">
            <i class="fas fa-exchange-alt fa-rotate-90"></i>
        </a>*@
                @*<div class="dot hidden"></div>*@
                <div class="ring-container hidden">
                    <div class="ringring"></div>
                    <a class="backToNavigationWord" data-toggle="tooltip" title="Back to word">
                        <i class="fas fa-exchange-alt fa-rotate-90"></i>
                    </a>

                </div>
                <!-- <a class="addQuestionToWord rounded" data-toggle="tooltip" title="Add a question to selected word" onclick="applier.toggleSelection();"><i class="fas fa-plus"></i></a>-->
                @{Html.RenderPartial("_Description", Model); }

            </div>

        <div class="question-detail"></div>

    }
    else
    {
        @if (isResearcher || isAdmin)
        {
            <div class="page-header shadow">
                <div class="w-100 float-left position-relative ">
                    <div class="attribute-type-title">
                        <span> <i class="fas fa-book"></i>  <strong> @(Model.TypeText):</strong></span>
                    </div>
                    <h3> @Model.Name</h3>
                </div>
            </div>
            <form id="document-form" asp-action="@("Save" + Model.Type)" asp-controller="Book">

                <div class="page-header shadow ">
                    <div class="w-100 float-left position-relative py-4 px-3">
                        <div class="attribute-type-title">
                            <span><i class="fas fa-file-alt"></i> Create document here</span>
                        </div>

                        <button type="submit" class="custom-button float-right"> <i class="fas fa-save saveHtmlBtn" data-toggle="tooltip" data-placement="left" data-modalcall="true" data-id="@Model.Id" data-type="@Model.Type" title="Save the document"></i></button>

                    </div>
                </div>
                <input asp-for="Id" hidden />

                <textarea asp-for="Detail" class="tmceeditor"></textarea>

            </form>
            @*<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item mr-1">
                        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#Document" role="tab" aria-controls="Document" aria-selected="true">Create Document Manually</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#UploadDocument" role="tab" aria-controls="UploadDocument" aria-selected="false">Upload Document</a>
                    </li>

                </ul>
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="Document" role="tabpanel" aria-labelledby="pills-home-tab">

                    </div>
                    <div class="tab-pane fade" id="UploadDocument" role="tabpanel" aria-labelledby="pills-profile-tab">
                        @{
                            Html.RenderPartial("~/Views/Shared/Common/_DocumentUpload.cshtml", Model);
                        }

                    </div>
                </div>*@

        }
        else
        {

            <div class="alert alert-danger text-center">
                No document available
            </div>

        }
    }
</div>

Web/Web/Management/Web/ManagementWeb/Views/Book/EditDetail.cshtml
@model AttributeViewModel

<div class="col col-12 col-sm-12  col-md-12 col-lg-12 ">

    <div class="page-header">
        <i class="fas fa-book"></i>
        @(
                    Model.Type
        ):
        <span> @Model.Name</span>

    </div>
    <form id="document-form" asp-action="@("Save"+Model.Type)" asp-controller="Book">

        <div class="page-header">
            <i class="fas fa-file-alt"></i> Create document here
            <div class="actionBtns float-md-right float-lg-right float-xl-right ">
                <a class="btn-outline-primary backBtn" href="@Url.Action(Model.Type,"Book")?id=@Model.Id"> <i class="fas fa-reply" data-toggle="tooltip" data-placement="left" data-modalcall="true" data-id="@Model.Id" data-type="@Model.Type" title="Back to document"></i></a>
                <button type="submit" class="border-0 m-0 p-0  btn-outline-primary saveBtn"> <i class="fas fa-save saveHtmlBtn" data-toggle="tooltip" data-placement="left" data-modalcall="true" data-id="@Model.Id" data-type="@Model.Type" title="Save the document"></i></button>
            </div>
        </div>

        <input asp-for="Id" hidden />
        <textarea asp-for="Detail" class="tmceeditor"></textarea>
    </form>
    @*<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item mr-1">
                <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#Document" role="tab" aria-controls="Document" aria-selected="true">Create Document Manually</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#UploadDocument" role="tab" aria-controls="UploadDocument" aria-selected="false">Upload Document</a>
            </li>

        </ul>
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="Document" role="tabpanel" aria-labelledby="pills-home-tab">

            </div>
            <div class="tab-pane fade" id="UploadDocument" role="tabpanel" aria-labelledby="pills-profile-tab">
               @{
                   Html.RenderPartial("~/Views/Shared/Common/_DocumentUpload.cshtml", Model);
               }

            </div>
        </div>*@
</div>

Web/Web/Management/Web/ManagementWeb/Views/Book/_DescriptionWrapper.cshtml
@model AttributeViewModel
@if(Model!=null) { 
<div id="@("Document_"+Model.Id)">
    <div class="question-header">
        <span class="unselectable">@Model.Name</span>
        <div class="actionBtns position-absolute">
           
            <i class="fas fa-reply backToWord" data-toggle="tooltip" data-placement="left" data-documentid="@Model.Id" title="Back To Last Position"></i>
            
            <i class="fas fa-times-circle closeDocumentBtn" data-toggle="tooltip" data-placement="left" data-documentid="@Model.Id" title="Close Document"> </i>
        </div>
    </div>
    <div class="page-outline pt-3 pr-5 pl-5 pb-3">
        @{ Html.RenderPartial("_Description", Model);           }
    </div>

</div>
            }